# Generated by Django 3.1.7 on 2023-08-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='sub_category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.sub_category'),
        ),
    ]
