# Generated by Django 3.1.7 on 2023-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20230827_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothe',
            name='clothes_orginal',
        ),
        migrations.AddField(
            model_name='clothe',
            name='clothes_original',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_originals/'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='clothes',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='clothes_mask',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_masks/'),
        ),
    ]
